// generated by "src\ts\meta\file generators\map menu sections 0 to 2 options.ts"

import { By } from 'selenium-webdriver';

export const label = By.xpath('//*[@id="settings"]/div/div[2]/div/ul[3]/li[3]/button/label');