// generated by "src\ts\meta\file generators\map menu sections 0 to 2 options.ts"

import { textOf, textError as textErrorOf } from '../../../../../../../src/ts/maps factory/label';
import { isDisplayedOf, displayError as displayErrorOf } from '../../../../../../../src/ts/maps factory/element';
import { getExpect, errorSome, errorSomeValue, rawAction, gotExpected } from '../../../../../../../src/ts/action layer and reporting tree';
import { label as locator } from './locators';

const name = 'your timeline label';
const visual = 'Your timeline';

export type displayError = displayErrorOf<typeof name>;
export type textError = textErrorOf<typeof name>;

export const isDisplayed: rawAction<errorSome<displayError, boolean>> = isDisplayedOf(name, locator)
export const check
  : rawAction<gotExpected<errorSome<textError, string>, errorSomeValue<typeof visual>>>
  = getExpect<errorSome<textError, string>, errorSomeValue<typeof visual>>
    ( { type: 'result'
      , value: visual }
    , textOf(name, locator) );